# Generated by Django 4.1.3 on 2022-11-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=50)),
                ('nivelAcademico', models.CharField(max_length=50)),
                ('cursosAsignados', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
    ]
